steps:
- name: 'mcr.microsoft.com/dotnet/core/sdk:3.1'
  entrypoint: 'dotnet'
  args: [ 'publish', '-c', 'Release' ]
artifacts:
  objects:
    location: 'gs://net-demo-output-bucket/target/'
    paths: ['./bin/Release/netcoreapp2.1/publish']