#added some comment
steps:
- name: 'mcr.microsoft.com/dotnet/core/sdk:3.1'
  entrypoint: 'dotnet'
  args: [ 'test' ]
- name: 'mcr.microsoft.com/dotnet/core/sdk:3.1'
  entrypoint: 'dotnet'
  args: [ 'publish', '-c', 'Release', '-r', 'win10-x64' ]
- name: 'mcr.microsoft.com/dotnet/core/sdk:3.1'
  entrypoint: 'bash'
  args: [ './tarring.sh' ]
#artifacts:
#  objects:
#    location: 'gs://net-demo-output-bucket/'
#    paths: ['/workspace/MessageUtil/bin/Release/netcoreapp3.1/win10-x64/messageutil-win10-x64.tar.gz']
- name: 'ubuntu'
  entrypoint: 'apt-get'
  args: [ 'update']
- name: 'ubuntu'
  entrypoint: 'apt-get'
  args: [ '-y', 'upgrade']
- name: 'ubuntu'
  entrypoint: 'apt-get'
  args: [ '-y', 'install', 'sshpass']
- name: 'ubuntu'
  entrypoint: 'bash'
  args: [ './filetrans.sh']
#- name: 'mcr.microsoft.com/dotnet/core/sdk:3.1'
#  entrypoint: 'ls'
#  args: [ '/workspace/MessageUtil/bin/Release/netcoreapp3.1/' ]
#- name: 'mcr.microsoft.com/dotnet/core/sdk:3.1'
#  entrypoint: 'ls'
#  args: [ './' ]